

_handler_0:
	iretd

_handler_1:
	iretd

_handler_2:
	iretd
	
_handler_3:
	iretd

_handler_4:
	iretd
	
_handler_5:
	iretd

_handler_6:
	iretd

_handler_7:
	iretd

_handler_8:
	iretd

_handler_9:
	iretd
	
_handler_10:
	iretd

_handler_11:
	iretd

_handler_12:
	iretd
	
_handler_13:
	iretd

_handler_14:
	iretd
	
_handler_15:
	iretd

_handler_16:
	iretd

_handler_17:
	iretd

_handler_18:
	iretd

_handler_19:
	iretd

_handler_20:
	iretd

_handler_21:
	iretd

_handler_22:
	iretd
	
_handler_23:
	iretd

_handler_24:
	iretd
	
_handler_25:
	iretd

_handler_26:
	iretd

_handler_27:
	iretd

_handler_28:
	iretd

_handler_29:
	iretd

_handler_30:
	iretd

_handler_31:
	iretd

_handler_32:
	sti
	call _send_eoi_i8259
	call _scheduler
	iretd
	
_handler_33:
	sti
	call _send_eoi_i8259
	call _keyboard
	iretd

_handler_34:
	iretd
	
_handler_35:
	iretd

_handler_36:
	iretd

_handler_37:
	iretd

_handler_38:
	iretd

_handler_39:
	iretd

_handler_40:
	iretd

_handler_41:
	iretd

_handler_42:
	iretd
	
_handler_43:
	iretd

_handler_44:
	iretd
	
_handler_45:
	iretd

_handler_46:
	iretd

_handler_47:
	iretd

_handler_48:
	iretd

_handler_49:
	iretd

_handler_50:
	iretd

_handler_51:
	iretd

_handler_52:
	iretd
	
_handler_53:
	iretd

_handler_54:
	iretd
	
_handler_55:
	iretd

_handler_56:
	iretd

_handler_57:
	iretd

_handler_58:
	iretd

_handler_59:
	iretd

_handler_60:
	iretd

_handler_61:
	iretd

_handler_62:
	iretd
	
_handler_63:
	iretd

_handler_64:
	iretd
	
_handler_65:
	iretd

_handler_66:
	iretd

_handler_67:
	iretd

_handler_68:
	iretd

_handler_69:
	iretd

_handler_70:
	iretd

_handler_71:
	iretd

_handler_72:
	iretd
	
_handler_73:
	iretd

_handler_74:
	iretd
	
_handler_75:
	iretd

_handler_76:
	iretd

_handler_77:
	iretd

_handler_78:
	iretd

_handler_79:
	iretd

_handler_80:
	iretd

_handler_81:
	iretd

_handler_82:
	iretd
	
_handler_83:
	iretd

_handler_84:
	iretd
	
_handler_85:
	iretd

_handler_86:
	iretd

_handler_87:
	iretd

_handler_88:
	iretd

_handler_89:
	iretd

_handler_90:
	iretd

_handler_91:
	iretd

_handler_92:
	iretd
	
_handler_93:
	iretd

_handler_94:
	iretd
	
_handler_95:
	iretd

_handler_96:
	iretd

_handler_97:
	iretd

_handler_98:
	iretd

_handler_99:
	iretd

_handler_100:
	iretd

_handler_101:
	iretd

_handler_102:
	iretd
	
_handler_103:
	iretd

_handler_104:
	iretd
	
_handler_105:
	iretd

_handler_106:
	iretd

_handler_107:
	iretd

_handler_108:
	iretd

_handler_109:
	iretd

_handler_110:
	iretd

_handler_111:
	iretd

_handler_112:
	iretd
	
_handler_113:
	iretd

_handler_114:
	iretd
	
_handler_115:
	iretd

_handler_116:
	iretd

_handler_117:
	iretd

_handler_118:
	iretd

_handler_119:
	iretd

_handler_120:
	iretd

_handler_121:
	iretd

_handler_122:
	iretd
	
_handler_123:
	iretd

_handler_124:
	iretd
	
_handler_125:
	iretd

_handler_126:
	iretd

_handler_127:
	iretd

_handler_128:
	call _syscall
	iretd

_handler_129:
	iretd

_handler_130:
	iretd

_handler_131:
	iretd

_handler_132:
	iretd
	
_handler_133:
	iretd

_handler_134:
	iretd
	
_handler_135:
	iretd

_handler_136:
	iretd

_handler_137:
	iretd

_handler_138:
	iretd

_handler_139:
	iretd

_handler_140:
	iretd

_handler_141:
	iretd

_handler_142:
	iretd
	
_handler_143:
	iretd

_handler_144:
	iretd
	
_handler_145:
	iretd

_handler_146:
	iretd

_handler_147:
	iretd

_handler_148:
	iretd

_handler_149:
	iretd

_handler_150:
	iretd

_handler_151:
	iretd

_handler_152:
	iretd
	
_handler_153:
	iretd

_handler_154:
	iretd
	
_handler_155:
	iretd

_handler_156:
	iretd

_handler_157:
	iretd

_handler_158:
	iretd

_handler_159:
	iretd

_handler_160:
	iretd

_handler_161:
	iretd

_handler_162:
	iretd
	
_handler_163:
	iretd

_handler_164:
	iretd
	
_handler_165:
	iretd

_handler_166:
	iretd

_handler_167:
	iretd

_handler_168:
	iretd

_handler_169:
	iretd


_handler_170:
	iretd

_handler_171:
	iretd

_handler_172:
	iretd
	
_handler_173:
	iretd

_handler_174:
	iretd
	
_handler_175:
	iretd

_handler_176:
	iretd

_handler_177:
	iretd

_handler_178:
	iretd

_handler_179:
	iretd

_handler_180:
	iretd

_handler_181:
	iretd

_handler_182:
	iretd
	
_handler_183:
	iretd

_handler_184:
	iretd
	
_handler_185:
	iretd

_handler_186:
	iretd

_handler_187:
	iretd

_handler_188:
	iretd

_handler_189:
	iretd

_handler_190:
	iretd

_handler_191:
	iretd

_handler_192:
	iretd
	
_handler_193:
	iretd

_handler_194:
	iretd
	
_handler_195:
	iretd

_handler_196:
	iretd

_handler_197:
	iretd

_handler_198:
	iretd

_handler_199:
	iretd

_handler_200:
	iretd

_handler_201:
	iretd

_handler_202:
	iretd
	
_handler_203:
	iretd

_handler_204:
	iretd
	
_handler_205:
	iretd

_handler_206:
	iretd

_handler_207:
	iretd

_handler_208:
	iretd

_handler_209:
	iretd

_handler_210:
	iretd

_handler_211:
	iretd

_handler_212:
	iretd
	
_handler_213:
	iretd

_handler_214:
	iretd
	
_handler_215:
	iretd

_handler_216:
	iretd

_handler_217:
	iretd

_handler_218:
	iretd

_handler_219:
	iretd

_handler_220:
	iretd

_handler_221:
	iretd

_handler_222:
	iretd
	
_handler_223:
	iretd

_handler_224:
	iretd
	
_handler_225:
	iretd

_handler_226:
	iretd

_handler_227:
	iretd

_handler_228:
	iretd

_handler_229:
	iretd

_handler_230:
	iretd

_handler_231:
	iretd

_handler_232:
	iretd
	
_handler_233:
	iretd

_handler_234:
	iretd
	
_handler_235:
	iretd

_handler_236:
	iretd

_handler_237:
	iretd

_handler_238:
	iretd

_handler_239:
	iretd

_handler_240:
	iretd

_handler_241:
	iretd

_handler_242:
	iretd
	
_handler_243:
	iretd

_handler_244:
	iretd
	
_handler_245:
	iretd

_handler_246:
	iretd

_handler_247:
	iretd

_handler_248:
	iretd

_handler_249:
	iretd

_handler_250:
	iretd

_handler_251:
	iretd

_handler_252:
	iretd
	
_handler_253:
	iretd

_handler_254:
	iretd
	
_handler_255:
	iretd
